### PR TITLE
ShowPlaylistView

### PR DESCRIPTION
**Pull request by asta12**
Issue #14 

Creates the ShowPlaylistView.

Currently there is some testdata. We will change this once we have real data.

There is also an editbutton. Right now it just prints. later we will route it to an editPlaylistView.

### CODE REVIEW

**Comment by AnnaSkantz** [comment]
Would be nice to take inspiration from the SearchResultsView in branch (issue-6-create-playlists) and display the name + artist + thumbnail the same way when you expand the playlist.

image

**Review by alevarn — APPROVED** [review]
LGTM! If you want you should be able to use `props.model.playlists` now instead of the example playlists.

**Comment by asta12** [comment]
I will change the CSS to better match the SearchResultsView and change the test data out for the real data.

**Comment by AnnaSkantz** [comment]
Looks good!

**Review by alevarn — APPROVED** [review]
LGTM!

**Pull request merged**
