### PR TITLE
Issue 69, 70, 71. User evaluations, navbar, register and l

### PR DESCRIPTION
**Pull request by kanova98**
This PR solves #71 #69 #70 

IMPORTANT, this PR is built on the pr solving the game evaluation issues, that one should be merged prior!

### CODE REVIEW

**Review by alevarn — APPROVED** [review]
LGTM!

**Comment by asta12** [comment]
The navbar text is still pale and a bit hard to read.

**Comment by AnnaSkantz** [comment]
I think that the text "You are logged in as <name>" should be removed. Would be nice with some other solution to show which user is currently signed in. 
The reason: 1. the text is a bit too long and 2. it kind of merges together with the Logout button so that you do not see that it is a button.

A suggestion would be to display the profile picture inside a circle and have the username next to it in some way.

**Comment by asta12** [comment]
Don't forget to update USER_EVALUATION.md

**Pull request merged**
