### PR TITLE
add changes to profile and profile pic in navbar

### PR DESCRIPTION
**Pull request by kanova98**
Change styling of profile a bit and add the profile picture to the navbar.

Please check if you think profile looks good, I didn't quite get it the way I wanted so if you feel like we should keep the old design let me know.

### CODE REVIEW

**Comment by AnnaSkantz** [comment]
Don't forget to link to the connected issues in the PR :)

**Comment by AnnaSkantz** [comment]
I think it looks good!

**Review by AnnaSkantz — APPROVED** [review]

**Comment by alevarn** [comment]
Solve merge conflict @kanova98.

**Review by alevarn — APPROVED** [review]
The profile picture to the left of the username? Maybe that looks better. You can decide.

**Comment by kanova98** [comment]
Think I solved the merge conflict now

**Pull request merged**
